development:
  adapter: postgresql
  encoding: utf8
  database: say-waot_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: say-waot_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: say-waot_production
  pool: 5